# Databricks notebook source
#If you wish to ingest a new CODR table, simply add the table's name and PID to the respective list below. 
#It may be worthwhile to refactor this code to read this data source data from an excel sheet instead.  

class Table:
  def __init__(self, indicator, PID):
    self.indicator = indicator
    self.PID = PID
    
class Theme:
    def __init__(self, tables, storage_path):
        self.tables = tables
        self.storage_path = storage_path

international_trade = [
    Table("Trade in goods by exporter characteristics, by enterprise employment size and industry", "12100094"),
    Table("Trade in goods by exporter characteristics, by industry of establishment and province/territory", "12100098"),
    Table("Trade in goods by exporter characteristics, by industry of establishment and census metropolitan area","12100138"),
    Table("Trade in goods by exporter characteristics, by country of destination","12100104"),
    Table("Trade in goods by exporter characteristics, by enterprise employment size and export size","12100097"),
    Table("Trade in goods by exporter characteristics, by industry of enterprise and number of partner countries","12100092"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and industry","12100106"),
    Table("Trade in goods by importer characteristics, by industry and census metropolitan area","12100139"),
    Table("Trade in goods by importer characteristics, by country of origin","12100114"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and import size","12100111"),
    Table("Trade in goods by importer characteristics, by industry and related parties","12100112"),
    Table("Trade in goods by importer characteristics, by industry and number of partner countries","12100105"),
]

output = [
    Table("GDP at basic prices, by industry, monthly, industry detail", "36100434"),
    Table("GDP at basic prices, by industry, provinces and territories", "36100402"),
]

labour_market = [
    Table("Employment by class of worker and industry, seasonally adjusted", "14100288"),
    Table("Employment by industry, monthly, seasonally adjusted", "14100355"),
    Table("Download Employment by establishment size, monthly, unadjusted for seasonality", "14100067"),
    Table("Employment by industry by CMA, three-month moving average, unadjusted for seasonality", "14100379"),
    Table("Labour force characteristics by province and CMA, three-month moving average, seasonally adjusted", "14100380"),
    Table("Labour force characteristics by territory, three-month moving average, seasonally adjusted", "14100292"),
    Table("Labour force characteristics by province and economic region, three-month moving average, unadjusted for seasonality", "14100387"),
    Table("Job vacancies, payroll employees, job vacancy rate, and average offered hourly wage by provinces/territories and economic regions, quarterly, unadjusted for seasonality", "14100325"), 
    Table("Job vacancies, payroll employees, job vacancy rate, and average offered hourly wage by industry sector, quarterly, unadjusted for seasonality", "14100326"),
    Table("Job vacancies, proportion of job vacancies and average offered hourly wage by selected characteristics, quarterly, unadjusted for seasonality", "14100328"),
    Table("Job vacancies, payroll employees, and job vacancy rate by provinces and territories, monthly, unadjusted for seasonality", "14100371"),
    Table("Job vacancies, payroll employees, and job vacancy rate by industry sector, monthly, unadjusted for seasonality", "14100372"),
    Table("Employment and average weekly earnings (including overtime) for all employees by province and territory, monthly, seasonally adjusted", "14100223"),
    Table("Fixed weighted index of average hourly earnings for all employees, by industry, monthly", "14100213"),
    Table("Employment insurance beneficiaries (regular benefits) by census metropolitan category, monthly, seasonally adjusted","14100322")

]

canadian_business = [
    Table("Canadian Business Counts, with employees", "33100395"),
    Table("Canadian Business Counts, without employees", "33100396"),
    Table("Canadian Business Counts, with employees, census metropolitan areas and census subdivisions", "33100397"),
    Table("Experimental estimates for business openings and closures for Canada, provinces and territories, census metropolitan areas, seasonally adjusted", "33100270"),
    Table("Experimental indexes of economic activity in the provinces and territories", "36100633"),
    Table("Real-time Local Business Condition Index (RTLBCI)", "33100398"),
    Table("Quarterly financial statistics for enterprises", "33100226"),
]

canadian_survey_on_business_conditions = [
    Table("Business or organization expectations over the next three months, first quarter of 2022", "33100468"),
    Table("Business or organization obstacles over the next three months, first quarter of 2022", "33100469"),
    Table("Business or organization expectations of how long various obstacles will last, first quarter of 2022", "33100470"),
    Table("Business or organization change in supply chain challenges over the last three months, first quarter of 2022", "33100471"),
    Table("Business or organization expectations of change in supply chain challenges over the next three months, first quarter of 2022", "33100472"),
    Table("Regions business or organization sourced inputs, products or supplies from over the last 12 months, first quarter of 2022", "33100473"),
    Table("Strategies business or organization uses to address supply chain challenges, first quarter of 2022", "33100474"),
    Table("Business or organization plans to adjust supply chain over the next 12 months, first quarter of 2022", "33100475"),
    Table("Plans to expand or restructure business or organization or acquire other businesses or organizations over the next 12 months, first quarter of 2022", "33100476"),
    Table("Plans to transfer, sell, or close business over the next 12 months, first quarter of 2022", "33100477"),
    Table("Likelihood of business or organization to pass on any increases in its costs to customers over the next 12 months, first quarter of 2022", "33100478"),
    Table("Change in average wages expected over the next 12 months, first quarter of 2022", "33100479"),
    Table("Average change in average wages expected over the next 12 months, first quarter of 2022", "33100480"),
    Table("Plans regarding recruitment, retention and training over the next 12 months, first quarter of 2022", "33100481"),
    Table("Liquidity and access to liquidity over the next three months, first quarter of 2022", "33100482"),
    Table("Ability for the business or organization to take on more debt, first quarter of 2022", "33100483"),
    Table("Percentage of workforce anticipated to work on-site or remotely over the next three months, first quarter of 2022", "33100484"),
    Table("Average percentage of workforce anticipated to work on-site or remotely over the next three months, first quarter of 2022", "33100485"),
    Table("Technology as a limiting factor in having more employees work remotely over the next three months, first quarter of 2022", "33100486"),
    Table("Plans to adopt new or additional digital technologies over the next 12 months, first quarter of 2022", "33100487"),
    Table("Future outlook for the business or organization over the next 12 months, first quarter of 2022", "33100488"),
    Table("Revenues from 2021 compared with 2019", "33100489"),
    Table("Percentage of women and men in management positions, first quarter of 2022", "33100490"),
    Table("Average percentage of women and men in management positions, first quarter of 2022", "33100491"),
    Table("Private sector business counts by majority ownership, first quarter of 2022", "33100492"),
    Table("Business or organization expectations over the next three months, second quarter of 2022", "33100503"),
    Table("Business or organization obstacles over the next three months, second quarter of 2022", "33100504"),
    Table("Business or organization expected impacts of labour-related obstacles over the next three months, second quarter of 2022", "33100505"),
    Table("Business or organization challenges with recruiting and retaining staff compared with 12 months ago, second quarter of 2022", "33100506"),
    Table("Business or organization expectations of how long supply chain obstacles will last, second quarter of 2022", "33100507"),
    Table("Business or organization change in supply chain challenges over the last three months, second quarter of 2022", "33100508"),
    Table("Business or organization expectations of change in supply chain challenges over the next three months, second quarter of 2022", "33100509"),
    Table("Regions business or organization sourced inputs, products or supplies from over the last 12 months, second quarter of 2022", "33100510"),
    Table("Business or organization plans to adjust supply chain over the next 12 months, second quarter of 2022", "33100511"),
    Table("Business or organization plans to relocate supply chain activities over the next 12 months, second quarter of 2022", "33100512"),
    Table("Plans to expand or restructure business or organization or acquire other businesses or organizations over the next 12 months, second quarter of 2022", "33100513"),
    Table("Plans to transfer, sell, or close business over the next 12 months, second quarter of 2022", "33100514"),
    Table("Business or organization expectations of increases in energy expenses over the next three months, second quarter of 2022", "33100515"),
    Table("Business or organization expectations of inflation to be a bigger issue when discussing wage increases with employees over the next 12 months, second quarter of 2022", "33100516"),
    Table("Changes business or organization plans to make over the next 12 months, second quarter of 2022", "33100517"),
    Table("Percentage and average percentage of total sales made online in 2021, second quarter of 2022", "33100518"),
    Table("Investments in online sales and e-commerce capabilities over the next 12 months, second quarter of 2022", "33100519"),
    Table("Business' or organization's plans to take any new or additional cybersecurity actions over the next 12 months, second quarter of 2022", "33100520"),
    Table("New goods or services innovations, or any new business process innovations introduced since 2020, second quarter of 2022", "33100521"),
    Table("Group that primarily developed new goods or services innovations, second quarter of 2022", "33100522"),
    Table("Group that primarily developed new business process innovations, second quarter of 2022", "33100523"),
    Table("Business or organization introducing innovations in response to the COVID-19 pandemic or the conditions it caused since 2020, second quarter of 2022", "33100524"),
    Table("Impact of the COVID-19 pandemic on business' or organization's activities related to innovation, second quarter of 2022", "33100525"),
    Table("Ability for the business or organization to take on more debt, second quarter of 2022", "33100526"),
    Table("Percentage of workforce anticipated to work on-site or remotely over the next three months, second quarter of 2022", "33100527"),
    Table("Average percentage of workforce anticipated to work on-site or remotely over the next three months, second quarter of 2022", "33100528"),
    Table("Business' or organization's current overall position compared with 2019, second quarter of 2022", "33100529"),
    Table("Business or organization expectations over the next three months, first quarter of 2022", "33100468"),
    Table("Business or organization expectations over the next three months, fourth quarter of 2021", "33100399"),
    Table("Business or organization obstacles over the next three months, fourth quarter of 2021", "33100400"),
    Table("Business or organization expectations of how long various obstacles will last, fourth quarter of 2021", "33100401"),
    Table("Plans to expand or restructure business or organization or acquire other businesses or organizations in the next 12 months, fourth quarter of 2021", "33100402"),
    Table("Plans to transfer, sell, or close business in the next 12 months, fourth quarter of 2021", "33100403"),
    Table("Business or organization awareness of trade agreements, fourth quarter of 2021", "33100404"),
    Table("Trade agreements business or organization currently carries out trade under, fourth quarter of 2021", "33100405"),
    Table("Primary reason business or organization does not carry out trade under the Canada-United States-Mexico Agreement (CUSMA), fourth quarter of 2021", "33100406"),
    Table("Primary reason business or organization does not carry out trade under the Canadian-European Union Comprehensive Economic and Trade Agreement (CETA), fourth quarter of 2021", "33100407"),
    Table("Primary reason business or organization does not carry out trade under the Comprehensive and Progressive Agreement for Trans-Pacific Partnership (CPTPP), fourth quarter of 2021", "33100408"),
    Table("Percentage of import purchases digitally ordered in the last 12 months, fourth quarter of 2021", "33100409"),
    Table("Digital methods used by business or organization to order goods from suppliers in other countries in the last 12 months, fourth quarter of 2021", "33100410"),
    Table("Digital methods used by business or organization to order services from suppliers in other countries in the last 12 months, fourth quarter of 2021", "33100411"),
    Table("Percentage of import purchases of services digitally delivered to business or organization ordered digitally from suppliers in other countries in the last 12 months, fourth quarter of 2021", "33100412"),
    Table("Change in purchases of services digitally delivered to business or organization from suppliers in other countries in the last 12 months, fourth quarter of 2021", "33100413"),
    Table("Impact of ransomware incidents on the business or organization in the last 12 months, fourth quarter of 2021", "33100414"),
    Table("Business or organization reporting of ransomware attack to insurance company in the last 12 months, fourth quarter of 2021", "33100415"),
    Table("Business or organization plans regarding recruitment, retention and training, fourth quarter of 2021", "33100416"),
    Table("Expected impact of the absence of government support programs on the survival of business or organization, fourth quarter of 2021", "33100417"),
    Table("Expected level of challenge business or organization has in repaying funding received from repayable government support programs put in place because of the COVID-19 pandemic, fourth quarter of 2021", "33100418"),
    Table("Liquidity and access to liquidity over the next three months, fourth quarter of 2021", "33100419"),
    Table("Ability for the business or organization to take on more debt, fourth quarter of 2021", "33100420"),
    Table("Percentage of workforce anticipated to work on-site or telework over the next three months, fourth quarter of 2021", "33100421"),
    Table("Average percentage of workforce anticipated to work on-site or telework over the next three months, fourth quarter of 2021", "33100422"),
    Table("Percentage of employees based in a different province or territory as employer that are anticipated to telework exclusively, fourth quarter of 2021", "33100423"),
    Table("Average percentage of employees based in a different province or territory as employer that are anticipated to telework exclusively, fourth quarter of 2021", "33100424"),
    Table("Business or organization status on reviewing cybersecurity policies in response to employees working remotely, fourth quarter of 2021", "33100425"),
    Table("Future outlook over the next 12 months, fourth quarter of 2021", "33100426"),
    Table("Sales expectations from October to December 2021 compared with October to December 2019, fourth quarter of 2021", "33100427"),
    Table("Business or organization expectations over the next three months, third quarter of 2021", "33100363"),
    Table("Business or organization obstacles over the next three months, third quarter of 2021", "33100364"),
    Table("Plans to expand or restructure business or acquire other businesses in the next 12 months, third quarter of 2021", "33100365"),
    Table("Plans to transfer, sell, or close business in the next 12 months, third quarter of 2021", "33100366"),
    Table("Percentage of export sales digitally ordered in the last 12 months, third quarter of 2021", "33100367"),
    Table("Digital methods used by customers or clients in other countries to order goods in the last 12 months, third quarter of 2021", "33100368"),
    Table("Digital methods used by customers or clients in other countries to order services in the last 12 months, third quarter of 2021", "33100369"),
    Table("Methods used to deliver services digitally ordered by clients or customers in other countries in the last 12 months", "33100370"),
    Table("Change in sales of services digitally delivered to customers or clients in other countries in the last 12 months", "33100371"),
    Table("Preferred method for digitally delivering services to customers or clients in other countries, third quarter of 2021", "33100372"),
    Table("Environmental practices currently in place or to be implemented by businesses or organizations in the next 12 months", "33100373"),
    Table("Main barrier businesses or organizations face in adopting more green practices in the next 12 months", "33100374"),
    Table("Sources or expected sources of personal protective equipment or supplies", "33100375"),
    Table("Personal protective equipment or supplies businesses or organizations have manufactured since March 2020", "33100376"),
    Table("Personal protective equipment or supplies businesses plan to manufacture 12 months from now", "33100377"),
    Table("COVID-19 Rapid Test kit usage over the last month, third quarter of 2021", "33100378"),
    Table("Percentage of on-site employees tested with COVID-19 Rapid Test kits at least once over the last month, third quarter of 2021", "33100379"),
    Table("Frequency on-site employees were tested using COVID-19 Rapid Test kits over the last month, third quarter of 2021", "33100380"),
    Table("Business or organization plans to start using COVID-19 Rapid Test kits to test on-site employees for COVID-19 infection in the next three months, third quarter of 2021", "33100381"),
    Table("Reasons business or organization does not have plans to start using COVID-19 Rapid Test kits in the next three months, third quarter of 2021", "33100382"),
    Table("Sources of funding approved or received due to the COVID-19 pandemic, third quarter of 2021", "33100383"),
    Table("Reasons business or organization did not access any funding or credit due to the COVID-19 pandemic, third quarter of 2021", "33100384"),
    Table("Liquidity and access to liquidity over the next three months, third quarter of 2021", "33100385"),
    Table("Ability for the business or organization to take on more debt, third quarter of 2021", "33100386"),
    Table("Outsourcing of tasks, projects or short contracts to freelancers or gig workers by the business or organization in the last 12 months", "33100387"),
    Table("Business or organization usage of third-party digital platforms, applications or websites to outsource tasks, projects or short contracts in the last 12 months", "33100388"),
    Table("Types of business or organizational activities outsourced through third-party digital platforms, applications or websites", "33100389"),
    Table("Businesses or organizations that bid on tasks, projects or short contracts using third-party digital platforms, applications or websites in the last 12 months", "33100390"),
    Table("Percentage of workforce anticipated to continue to primarily telework once the COVID-19 pandemic is over", "33100391"),
    Table("Businesses or organizations anticipated to shrink office locations due to the workforce teleworking", "33100392"),
    Table("Future outlook over the next 12 months, third quarter of 2021", "33100393"),
    Table("Length of time businesses or organizations expect to continue to operate at its current level of revenue and expenditures, third quarter of 2021", "33100394"),
    Table("Business or organization expectations over the next three months, by business characteristics, second quarter of 2021", "33100337"),
    Table("Business or organization obstacles over the next three months, by business characteristics, second quarter of 2021", "33100338"),
    Table("Plans to expand or restructure business or acquire other businesses in the next 12 months, by business characteristics, second quarter of 2021", "33100339"),
    Table("Plans to transfer, sell, or close business in the next 12 months, by business characteristics, second quarter of 2021", "33100340"),
    Table("Reason business or organization is planning to close in the next 12 months, by business characteristics, second quarter of 2021", "33100341"),
    Table("Changes to the workforce over the next 12 months, by business characteristics", "33100342"),
    Table("Intentions behind spending on employee training over the next 12 months, by business characteristics", "33100343"),
    Table("Extent to which businesses or organizations expect to face various challenges with regards to the workforce over the next three months, by business characteristics, second quarter of 2021", "33100344"),
    Table("Investments in online sales and e-commerce capabilities over the next 12 months, by business characteristics", "33100345"),
    Table("Outreach to new customers over the last 12 months, by business characteristics", "33100346"),
    Table("Primary international activity businesses or organizations plans to focus on over the next 12 months, by business characteristics", "33100347"),
    Table("Primary international market businesses or organizations plans to focus on over the next 12 months, by business characteristics", "33100348"),
    Table("Sources for advice related to opportunities or challenges businesses or organizations may consult over the next 12 months, by business characteristics", "33100349"),
    Table("Sources of funding approved or received due to the COVID-19 pandemic, by business characteristics, second quarter of 2021", "33100350"),
    Table("Reasons business or organization did not access any funding or credit due to the COVID-19 pandemic, by business characteristics, second quarter of 2021", "33100351"),
    Table("Impact on credit rating due to the pandemic, by business characteristics, second quarter of 2021", "33100352"),
    Table("Liquidity and access to liquidity over the next three months, by business characteristics, second quarter of 2021", "33100353"),
    Table("Ability for the business or organization to take on more debt, by business characteristics, second quarter of 2021", "33100354"),
    Table("Likelihood of various measures being permanently adopted once the COVID-19 pandemic is over, by business characteristics, second quarter of 2021", "33100355"),
    Table("Technologies the business or organization plan to adopt or incorporate over the next 12 months, by business characteristics, second quarter of 2021", "33100356"),
    Table("Challenges faced when adopting or incorporating technologies, by business characteristics", "33100357"),
    Table("Cybersecurity incidents in 2020 compared with 2019, by business characteristics", "33100358"),
    Table("Impact of 5G availability on business or organization operations or services over the next 12 months, by business characteristics", "33100359"),
    Table("Impact of changes to international trade agreements or provisions, by business characteristics", "33100360"),
    Table("Future outlook over the next 12 months, by business characteristics, second quarter of 2021", "33100361"),
    Table("Length of time businesses or organizations expect to continue to operate at its current level of revenue and expenditures, by business characteristics, second quarter of 2021", "33100362"),
    Table("Business or organization expectations over the next three months, by business characteristics, first quarter of 2021", "33100307"),
    Table("Business or organization obstacles over the next three months, by business characteristics, first quarter of 2021", "33100308"),
    Table("COVID-19 impact on business or organization status, by business characteristics, first quarter of 2021", "33100309"),
    Table("Plans to expand or restructure business or acquire other businesses in the next year, by business characteristics, first quarter of 2021", "33100310"),
    Table("Plans to transfer, sell, or close business, by business characteristics, first quarter of 2021", "33100311"),
    Table("Workforce changes, by business characteristics", "33100312"),
    Table("Employee support provided due to COVID-19, by business characteristics", "33100313"),
    Table("Extent to which businesses or organizations expect to face various challenges with regards to the workforce, by business characteristics", "33100314"),
    Table("Current or planned actions or measures in place due to the COVID-19 pandemic, by business characteristics, first quarter of 2021", "33100315"),
    Table("Percentage of total sales made online in 2019 and 2020, by business characteristics", "33100316"),
    Table("Business or organization revenue from 2020 compared with 2019, by business characteristics", "33100317"),
    Table("Business or organization expenses from 2020 compared with 2019, by business characteristics", "33100318"),
    Table("Impacts on various expenditures due to COVID-19, by business characteristics, first quarter of 2021", "33100319"),
    Table("Approved funding or credit due to the COVID-19 pandemic, by business characteristics, first quarter of 2021", "33100320"),
    Table("Reasons business or organization did not access any funding or credit due to the COVID-19 pandemic, by business characteristics, first quarter of 2021", "33100321"),
    Table("Ability for the business or organization to take on more debt, by business characteristics, first quarter of 2021", "33100322"),
    Table("Contributions to the community due to COVID-19, by business characteristics", "33100323"),
    Table("Expected level of difficulty in procuring personal protective equipment or supplies, by business characteristics, first quarter of 2021", "33100324"),
    Table("Reasons difficulty is expected in procuring personal protective equipment or supplies, by business characteristics, first quarter of 2021", "33100325"),
    Table("Likelihood of various measures being permanently adopted once the COVID-19 pandemic is over, by business characteristics, first quarter of 2021", "33100326"),
    Table("Technologies adopted or incorporated, by business characteristics, first quarter of 2021", "33100327"),
    Table("Climate change investments, by business characteristics", "33100328"),
    Table("Percentage of workforce anticipated to continue primarily teleworking or working remotely over the next three months, by business characteristics", "33100329"),
    Table("Length of time businesses or organizations expect to continue to operate at its current level of revenue and expenditures, by business characteristics, first quarter of 2021", "33100330"),
    Table("Business or organization obstacles over the last three months, by business characteristics, third quarter of 2020", "33100273"),
    Table("Percentage of workforce teleworking or working remotely, and percentage of workforce anticipated to continue primarily teleworking or working remotely after the pandemic, by business characteristics", "33100274"),
    Table("Extent to which use of various methods to provide goods or services to customers or users is expected to change over the next three months, by business characteristics", "33100275"),
    Table("Impact of COVID-19 on business or organization status, by business characteristics, third quarter of 2020", "33100276"),
    Table("Current or planned actions or measures in place due to COVID-19, by business characteristics, third quarter of 2020", "33100277"),
    Table("Current or planned actions or measures in place for parents employed by the business or organization, by business characteristics", "33100278"),
    Table("Layoffs since the start of the COVID-19 pandemic, by business characteristics", "33100279"),
    Table("Of businesses where at least one employee was laid off, percentage of workforce laid off and rehired due to COVID-19, by business characteristics", "33100280"),
    Table("Business or organization revenue from August 2020 compared with August 2019, by business characteristics", "33100281"),
    Table("Business or organization expenses from August 2020 compared with August 2019, by business characteristics", "33100282"),
    Table("COVID-19 impacts on various expenditures, by business characteristics, third quarter of 2020", "33100283"),
    Table("Approved funding or credit due to COVID-19, by business characteristics, third quarter of 2020", "33100284"),
    Table("Reasons business or organization did not access any funding or credit due to COVID-19, by business characteristics, third quarter of 2020", "33100285"),
    Table("Liquidity and access to liquidity, by business characteristics, third quarter of 2020", "33100286"),
    Table("Business or organization ability to take on more debt, by business characteristics, third quarter of 2020", "33100287"),
    Table("Business or organization space, by business characteristics", "33100288"),
    Table("Level of difficulty expected in procuring personal protective equipment or supplies, by business characteristics, third quarter of 2020", "33100289"),
    Table("Reasons why difficulty is expected in procuring personal protective equipment or supplies, by business characteristics, third quarter of 2020", "33100290"),
    Table("Likelihood of various measures being permanently adopted once the pandemic is over, by business characteristics, third quarter of 2020", "33100291"),
    Table("Statements regarding operations of the business or organization, by business characteristics", "33100292"),
    Table("Length of time businesses or organizations expect to continue to operate at current revenue and expenditures, by business characteristics", "33100293"),
    Table("Expectations of prices charged over the next three months, by business characteristics", "33100294"),
    Table("Expectations of number of employees employed by business or organization over the next three months, by business characteristics, third quarter of 2020", "33100295"),
    Table("Plans to acquire or invest in other businesses or organizations in the next year, by business characteristics, third quarter of 2020", "33100296"),
    Table("Plans to transfer, sell, or close, by business characteristics, third quarter of 2020", "33100297"),
    Table("Percentage of workforce teleworking or working remotely, and percentage of workforce expected to continue teleworking or working remotely after the pandemic, by business characteristics", "33100247"),
    Table("Methods used to conduct sales or secure orders remotely before and during the COVID-19 pandemic, by business characteristics", "33100248"),
    Table("Cyber security incidents in May 2020 compared to February 2020, by business characteristics", "33100249"),
    Table("Changes made by businesses to adapt to the COVID-19 pandemic, by business characteristics", "33100250"),
    Table("Staffing actions taken by businesses to adapt to the COVID-19 pandemic, by business characteristics", "33100251"),
    Table("Business revenue from April 2020 compared with April 2019, by business characteristics", "33100253"),
    Table("Business expenses from April 2020 compared with April 2019, by business characteristics", "33100254"),
    Table("Funding or credit approved due to COVID-19, by business characteristics, May 2020", "33100255"),
    Table("Percentage of workforce hired back after business was approved for the Canadian Emergency Wage Subsidy, by business characteristics", "33100256"),
    Table("Deferral of rent or mortgage payments owed by businesses, by business characteristics", "33100257"),
    Table("New products businesses have begun manufacturing, by business characteristics", "33100258"),
    Table("Personal protective equipment or supply needs, by business characteristics", "33100259"),
    Table("Difficulty procuring personal protective equipment or supplies, by business characteristics, May 2020", "33100260"),
    Table("Sources of personal protective equipment or supplies, by business characteristics", "33100261"),
    Table("Extent to which businesses are expecting to face various challenges with regards to recruitment and training, by business characteristics", "33100262"),
    Table("Likelihood of various measures being permanently adopted once COVID-19 pandemic is over, by business characteristics, May 2020", "33100263"),
    Table("Likelihood of various protective measures being implemented once transitioned to on-site work, by business characteristics", "33100264"),
    Table("Length of time businesses expect to continue to operate at current revenue and expenditures before having to consider further staffing actions, closure or bankruptcy, by business characteristics", "33100265"),
    Table("Business expectations of number of employees over the next three months, by business characteristics, May 2020", "33100266"),
    Table("Percentage of workforce teleworking or working remotely, and percentage of workforce able to carry out a majority of duties during the COVID-19 pandemic, by business characteristics", "33100228"),
    Table("Extent of various impacts experienced by businesses because of COVID-19, by business characteristics", "33100229"),
    Table("Changes made by businesses during the COVID-19 pandemic, by business characteristics", "33100230"),
    Table("Staffing actions taken by businesses during the COVID-19 pandemic, by business characteristics", "33100231"),
    Table("Percentage of workforce laid off because of COVID-19, by business characteristics", "33100232"),
    Table("Length of time businesses expect being able to remain fully or partially operational while social distancing measures are in place, by business characteristics", "33100233"),
    Table("Business revenue from January 1 to March 31, 2019, compared with January 1 to March 31, 2020, by business characteristics", "33100234"),
    Table("Length of time businesses expect to be able to continue to operate without a source of revenue as of February 1, 2020, by business characteristics", "33100235"),
    Table("Extent of various sources businesses relied on for updates on COVID-19, by business characteristics", "33100236"),
    Table("Impact of social distancing measures on businesses, by business characteristics", "33100237"),
    Table("Business practices tested or used while social distancing measures were in place, by business characteristics", "33100238"),
    Table("Change in expenditures to various business areas, by business characteristics", "33100239"),
    Table("Percentage of assets businesses have tried to liquidate due to COVID-19, by business characteristics", "33100240"),
    Table("Outcome of credit requests made by businesses to financial institutions due to COVID-19, by business characteristics", "33100241"),
    Table("Deferral of rent payments owed by businesses, by business characteristics", "33100242"),
    Table("New products businesses have begun manufacturing in response to requests from government, by business characteristics", "33100243"),
    Table("Length of time businesses require before being able to return to normal operations once social distancing measures are removed, by business characteristics", "33100244"),
    Table("Extent to which businesses expect to face various challenges with regards to recruitment and training, by business characteristics", "33100245"),
    Table("Occupational groups most needed in recovery period, by business characeristics", "33100246")
    
]

environmental = [
    Table("Climate change investments, by business characteristics", "33100328")
]

income_and_financial = [
    Table("Summary of charitable donors", "11100130"),
    Table("Tax filers with charitable donations by sex and age", "11100002"),
    Table("Tax filers with charitable donations by income", "11100003"),
    Table("elected characteristics of tax filers with Registered Retirement Savings Plan (RRSP) contributions", "11100044"),
    Table("Summary characteristics of Canadian tax filers (preliminary T1 Family File)", "11100047"),
    Table("Wages, salaries and commissions of tax filers aged 15 years and over by sex and age group", "11100072"),
    Table("Wages, salaries and commissions of tax filers aged 15 years and over by main industry sector and sex", "11100073"),
    Table("Tax filers by savers' characteristics, inactive", "11100040"), # archived
    Table("Tax filers by investors' characteristics, inactive", "11100042"), # archived
    Table("Canadian investment income, by characteristics of tax filers with investment income, inactive", "11100043"), # archived
    Table("Canadian capital gains, by characteristics of tax filers with capital gains, inactive", "11100048") # archived

    
]

trade_by_exporter_characteristics = [
    Table("Trade in goods by exporter characteristics, by enterprise employment size and number of partner countries", "12100091"),
    Table("Trade in goods by exporter characteristics, by industry of enterprise and number of partner countries", "12100092"),
    Table("Trade in goods by exporter characteristics, by enterprise employment size and concentration of exports (x 1,000)", "12100093"),
    Table("Trade in goods by exporter characteristics, by enterprise employment size and industry", "12100094"),
    Table("Trade in goods by exporter characteristics, by enterprise employment size and country of destination", "12100095"),
    Table("Trade in goods by exporter characteristics, by enterprise employment size and region type", "12100096"),
    Table("Trade in goods by exporter characteristics, by enterprise employment size and export size", "12100097"),
    Table("Trade in goods by exporter characteristics, by industry of establishment", "12100098"),
    Table("Trade in goods by exporter characteristics, by establishment employment size and number of partner countries", "12100103"),
    Table("Trade in goods by exporter characteristics, by country of destination", "12100104"),
    Table("Trade in goods by exporter characteristics, by census metropolitan area and number of partner countries", "12100137"),
    Table("Trade in goods by exporter characteristics, by industry of establishment and census metropolitan area (x 1,000)", "12100138")
    
]

trade_by_importer_characteristics = [
    Table("Trade in goods by importer characteristics, by enterprise employment size and number of partner countries", "12100071"),
    Table("Trade in goods by importer characteristics, by industry and number of partner countries", "12100105"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and industry", "12100106"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and concentration of imports (x 1,000)", "12100107"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and country of origin", "12100108"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and country of export", "12100109"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and region type", "12100110"),
    Table("Trade in goods by importer characteristics, by enterprise employment size and import size", "12100111"),
    Table("Trade in goods by importer characteristics, by industry and related parties", "12100112"),
    Table("Trade in goods by importer characteristics, by establishment employment size and number of partner countries", "12100113"),
    Table("Trade in goods by importer characteristics, by country of origin", "12100114"),
    Table("Trade in goods by importer characteristics, by country of export", "12100115"),
    Table("Trade in goods by importer characteristics, by census metropolitan area and number of partner countries", "12100131"),
    Table("Trade in goods by importer characteristics, by industry and census metropolitan area (x 1,000)", "12100139")
]

canadian_income_survey = [
    Table("Gini coefficients of adjusted market, total and after-tax income", "11100134"),
    Table("Low income statistics by age, sex and economic family type", "11100135"),
    Table("Percentage of persons in low income by sex", "11100135"),
    Table("Low income statistics by economic family type", "11100136"),
    Table("Market income, government transfers, total income, income tax and after-tax income by economic family type", "11100190"),
    Table("Income statistics by economic family type and income source", "11100191"),
    Table("Upper income limit, income share and average income by economic family type and income decile", "11100192"),
    Table("pper income limit, income share and average of adjusted market, total and after-tax income by income decile", "11100193"),
    Table("Low income cut-offs (LICOs) before and after tax by community size and family size, in constant dollars", "11100195"),
    Table("Low income measure (LIM) thresholds by income source and household size", "11100232"),
    Table("Distribution of market, total and after-tax income by economic family type, Canada, provinces and selected census metropolitan areas (CMAs)", "11100237"),
    Table("Distribution of market, total and after-tax income of individuals, Canada, provinces and selected census metropolitan areas", "11100238"),
    Table("Income of individuals by age group, sex and income source, Canada, provinces and selected census metropolitan areas", "11100239"),
    Table("Distribution of employment income of individuals by sex and work activity, Canada, provinces and selected census metropolitan areas", "11100240"),
    Table("Low income cut-offs (LICOs) before and after tax by community size and family size, in current dollars", "11100241"),
    Table("Market Basket Measure (MBM) thresholds for the reference family by Market Basket Measure region, component and base year", "11100066"),
    Table("Proportion of annual family income spent on child care, by economic family type", "11100080"),
    Table("Food insecurity by economic family type", "13100834"),
    Table("Food insecurity by age group and sex", "13100835"),
    Table("Unmet health care needs by sex and age group", "13100836"),
    Table("Average and median gender pay ratio in annual wages, salaries and commissions", "14100324"),
    Table("Percentage of the population aged 0 to 24 in low income, by age group and type of living arrangement", "37100129"),
    Table("Market Basket Measure (MBM) thresholds (2011 base) for reference family, by Market Basket Measure region and component, in current dollars and 2016 constant dollars, inactive", "11100230"), # archived
    Table("Canadian Income Survey (CIS), market income, government transfers, total income, income tax and after-tax income", "11100032"), # archived
    Table("Canadian Income Survey (CIS), median after-tax income, by economic family type, Canada, provinces and census metropolitan areas (CMAs)", "11100035"), # archived
    Table("Canadian Income Survey (CIS), persons in low income, Canada, provinces and census metropolitan areas (CMAs) (x 1,000)", "11100041"), # archived
    Table("Canadian Income Survey (CIS), persons in low income, Canada and provinces", "11100060") # archived
    
]

recovery = [
    Table("Labour force characteristics, three month moving average, seasonally adjusted (x 1,000)", "14100380"),
    Table("Employment insurance beneficiaries by census metropolitan category, monthly, unadjusted for seasonality", "14100137"),
    Table("Experimental estimates for business openings and closures for Canada, provinces and territories, census metropolitan areas, seasonally adjusted", "33100270"),
    Table("Consumer Price Index, monthly, not seasonally adjusted", "18100004"),
    Table("Manufacturing sales, by industry for 15 Selected Census Metropolitan Areas (x 1,000)", "16100011"),
    Table("Retail trade sales by province and territory (x 1,000)", "20100008"),
    Table("Building permits, by type of structure and type of work (x 1,000)", "34100066"),
    Table("Canada Mortgage and Housing Corporation, housing starts, by type of dwelling and market type in centres 10,000 and over, Canada, provinces, census metropolitan areas and large census agglomerations", "34100148"),
    Table("Canada Mortgage and Housing Corporation, housing starts, under construction and completions in selected census metropolitan areas, monthly", "34100154"),
    Table("Canada Mortgage and Housing Corporation, housing starts, under construction and completions in selected census metropolitan areas, monthly", "34100154"),
    Table("Canada Mortgage and Housing Corporation, absorptions and unabsorbed inventory, newly completed dwellings, by type of dwelling unit in census metropolitan areas", "34100149"),
    Table("Investment in Building Construction", "34100175"),
    Table("Canada Mortgage and Housing Corporation, vacancy rates, row and apartment structures of three units and over, privately initiated in census metropolitan areas, weighted average", "34100130"),
    Table("Canada Mortgage and Housing Corporation, vacancy rates, apartment structures of six units and over, privately initiated in census metropolitan areas", "34100127"),
    Table("Canada Mortgage and Housing Corporation, average rents for areas with a population of 10,000 and over", "34100133"),
    Table("New housing price index, monthly", "18100205"),
    Table("Residency ownership and property use by residential property type and period of construction", "46100054")
]

competitiveness_and_growth = [
    Table("Assets and debts held by economic family type, by age group, Canada, provinces and selected census metropolitan areas, Survey of Financial Security (x 1,000,000)", "11100016"),
    Table("Gross domestic product (GDP) at basic prices, by census metropolitan area (CMA) (x 1,000,000)", "36100468"),
    Table("Canadian Business Counts, with employees, census metropolitan areas and census subdivisions, December 2021", "33100495"),
    Table("Interprovincial and intraprovincial migrants, by census metropolitan area and census agglomeration of origin and destination, 2016 boundaries", "17100141"),
    Table("Population and dwelling counts: Census metropolitan areas, census agglomerations and census subdivisions (municipalities)", "98100003"),
    Table("Population estimates, July 1, by census metropolitan area and census agglomeration, 2016 boundaries", "17100135"),
    Table("Components of population change by census metropolitan area and census agglomeration, 2016 boundaries", "17100136")
]

codr_tables = {
    "Labour Market": Theme(labour_market, "/dbfs/mnt/bdl-lde/bronze/statcan/labour-market"),
    "Canadian Business": Theme(canadian_business, "/dbfs/mnt/bdl-lde/bronze/statcan/canadian-business"),
    "International Trade": Theme(international_trade, "/dbfs/mnt/bdl-lde/bronze/statcan/international-trade"),
    "Output": Theme(output, "/dbfs/mnt/bdl-lde/bronze/statcan/output"),
    "Environmental": Theme(environmental, "/dbfs/mnt/bdl-lde/bronze/statcan/environmental"),
    "CSBC": Theme(canadian_survey_on_business_conditions,"/dbfs/mnt/bdl-lde/bronze/statcan/canadian-survey-on-business-conditions"),
    "Recovery": Theme(recovery, "/dbfs/mnt/bdl-lde/bronze/statcan/recovery"),
    "Growth": Theme(competitiveness_and_growth, "/dbfs/mnt/bdl-lde/bronze/statcan/competitiveness-and-growth"),
    "CIS": Theme(canadian_income_survey, "/dbfs/mnt/bdl-lde/bronze/statcan/canadian-income-survey"),
    "Income and Financial": Theme(income_and_financial, "/dbfs/mnt/bdl-lde/bronze/statcan/income-and-financial"),
    "TEC": Theme(trade_by_exporter_characteristics, "/dbfs/mnt/bdl-lde/bronze/statcan/trade-by-exporter-characteristics"),
    "TIC": Theme(trade_by_importer_characteristics, "/dbfs/mnt/bdl-lde/bronze/statcan/trade-by-importer-characteristics")
}
